version: "3.4"
# As soon as will be released next stable docker version after 17.09, .Node.ID should be replaced to .Node.Hostname
services:
  builder:
    logging: &LOGGING
      driver: json-file
      options:
        max-size: "4m"
        max-file: "2"

  router:
    logging: *LOGGING

secrets:
  builder.crt.v3:
    external: true
  builder.key.v1:
    external: true