version: "3.6"
services:
  builder:
    image: electronuserland/build-service-builder
    environment:
      - BUILDER_HOST
      - BUILDER_PORT
      - DEBUG
      - PREFERRED_IP_VERSION
      - USE_EMBEDDED_ETCD
      - SNAP_DESTRUCTIVE_MODE
    ports:
      - target: ${BUILDER_PORT:-443}
        published: 443
        # http://docs.docker.com/engine/swarm/ingress/#bypass-the-routing-mesh
        mode: host
    secrets:
      # /etc/secrets instead of default /run/secrets because /run/secrets leads to unclear error on k8s (rancher)
      # tls.* names according to traefik/k8s nginx ingress controllers
      - source: builder.crt.v1
        target: /etc/secrets/tls.cert
      - source: builder.key.v1
        target: /etc/secrets/tls.key
    volumes:
      - type: tmpfs
        target: /builder-tmp
      - type: tmpfs
        target: /embedded-etcd

secrets:
  builder.crt.v1:
    file: ./certs/tls.cert
  builder.key.v1:
    file: ./certs/tls.key