apiVersion: v1
kind: Namespace
metadata:
  name: build-service
---
apiVersion: v1
data:
  tls.cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVM2Z0F3SUJBZ0lSQU4rYzhxNExEV2RwYmt1bm5aYktrUlF3Q2dZSUtvWkl6ajBFQXdJd0pERWkKTUNBR0ExVUVBeE1aWld4bFkzUnliMjR1WW5WcGJHUXViRzlqWVd3Z2NtOXZkREFlRncweE9UQTJNVFV5TWpJMwpNVE5hRncweU9UQTJNVEl5TWpJM01UTmFNQjh4SFRBYkJnTlZCQU1URkdWc1pXTjBjbTl1TG1KMWFXeGtMbXh2ClkyRnNNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVubWZwTlhXOHVGRmk5czRaanl6d2tyM2EKbnBWSnFGdGszclBsa2owdzVGWGk3UmZubXFIa1pLOUdZK0kyL1VnMEROQmtLNFVUbFNEdkh3bXlGU3hNSEtORwpNRVF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXCmdCU1diVHk4RjdnSlEwQTVOQTNsblZFMU44bU9OakFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUFXTk1HMmQyYUQKMjJtMjVhODlyT0FDTG1DWUlUNjVoOHgzTmpxYVNseXozZ0loQU11bnVWQ1piaXZpRGlJbU54UFE2a0d6WHJNbgo0ZktHSmcrNFZXdHF0ZXFpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lSQUo2bFdvSXJuaTFCdkt6dDJjekxvNXd3Q2dZSUtvWkl6ajBFQXdJd0pERWkKTUNBR0ExVUVBeE1aWld4bFkzUnliMjR1WW5WcGJHUXViRzlqWVd3Z2NtOXZkREFlRncweE9UQTJNVFV5TWpJMwpNVE5hRncweU9UQTJNVEl5TWpJM01UTmFNQ1F4SWpBZ0JnTlZCQU1UR1dWc1pXTjBjbTl1TG1KMWFXeGtMbXh2ClkyRnNJSEp2YjNRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVnlkdXVDVDJhY3VrMlFIMDYKeWFsL2I2TzdlVFRwT0hrM1VjamMrWlp0YTJ2QzIrYzFJS2NTQXdpbUtiVGJLK25SeFdXSmw5Wll4OVJUd2JSZgpRakQ2bzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVsbTA4dkJlNENVTkFPVFFONVoxUk5UZkpqall3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVDROSkRRQWsKeFhaWkEzZ2hHRmpmYzBJdjY1bUpyT2VsR0dOMzNvSzNpQjBDSVFDS1VDU3RpSU1VS1JyOHBvWU42MzY5MWRjaAowa1ZMRnJnRC82eUVUbVNBcXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUQ4YndmS2tjMER5eFJudHhvSUwrN3hLdmtieUpLTXk1ZitybUxxc0djcFlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbm1mcE5YVzh1RkZpOXM0Wmp5endrcjNhbnBWSnFGdGszclBsa2owdzVGWGk3UmZubXFIawpaSzlHWStJMi9VZzBETkJrSzRVVGxTRHZId215RlN4TUhBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: tls-8fb2mddt4h
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: builder
spec:
  ports:
  - nodePort: 30443
    port: 443
    protocol: TCP
  selector:
    app: builder
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
spec:
  ports:
  - port: 2379
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd0
  name: etcd0
spec:
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: server
    port: 2380
    targetPort: 2380
  selector:
    etcd_node: etcd0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd1
  name: etcd1
spec:
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: server
    port: 2380
    targetPort: 2380
  selector:
    etcd_node: etcd1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd2
  name: etcd2
spec:
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: server
    port: 2380
    targetPort: 2380
  selector:
    etcd_node: etcd2
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: builder
  name: builder
spec:
  selector:
    matchLabels:
      app: builder
  template:
    metadata:
      labels:
        app: builder
    spec:
      containers:
      - env:
        - name: BUILDER_HOST
          value: 0.0.0.0
        image: electronuserland/build-service-builder@sha256:88560aa85a2d088e14b92395d81900f416ae616285371509247fdd7dd3512ffc
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 300
          successThreshold: 1
          timeoutSeconds: 2
        name: builder
        ports:
        - containerPort: 443
          hostPort: 443
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 443
            scheme: HTTPS
          periodSeconds: 1
          successThreshold: 2
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/secrets
          name: tls
          readOnly: true
        - mountPath: /builder-tmp
          name: tmp
      terminationGracePeriodSeconds: 300
      volumes:
      - name: tls
        secret:
          secretName: tls-8fb2mddt4h
      - emptyDir:
          medium: Memory
        name: tmp
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd0
  name: etcd0
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - etcd0
    - --initial-advertise-peer-urls
    - http://etcd0:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://etcd0:2379
    - --initial-cluster
    - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
    - --initial-cluster-state
    - new
    - --data-dir
    - /data-dir
    image: quay.io/coreos/etcd:v3.3
    name: etcd0
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: server
    volumeMounts:
    - mountPath: /data-dir
      name: data-dir
  restartPolicy: Always
  volumes:
  - emptyDir:
      medium: Memory
    name: data-dir
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd1
  name: etcd1
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - etcd1
    - --initial-advertise-peer-urls
    - http://etcd1:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://etcd1:2379
    - --initial-cluster
    - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
    - --initial-cluster-state
    - new
    - --data-dir
    - /data-dir
    image: quay.io/coreos/etcd:v3.3
    name: etcd1
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: server
    volumeMounts:
    - mountPath: /data-dir
      name: data-dir
  restartPolicy: Always
  volumes:
  - emptyDir:
      medium: Memory
    name: data-dir
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd2
  name: etcd2
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - etcd2
    - --initial-advertise-peer-urls
    - http://etcd2:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://etcd2:2379
    - --initial-cluster
    - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
    - --initial-cluster-state
    - new
    - --data-dir
    - /data-dir
    image: quay.io/coreos/etcd:v3.3
    name: etcd2
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: server
    volumeMounts:
    - mountPath: /data-dir
      name: data-dir
  restartPolicy: Always
  volumes:
  - emptyDir:
      medium: Memory
    name: data-dir
