apiVersion: v1
kind: Namespace
metadata:
  name: build-service
---
apiVersion: v1
data:
  tls.cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVM2Z0F3SUJBZ0lSQU4rYzhxNExEV2RwYmt1bm5aYktrUlF3Q2dZSUtvWkl6ajBFQXdJd0pERWkKTUNBR0ExVUVBeE1aWld4bFkzUnliMjR1WW5WcGJHUXViRzlqWVd3Z2NtOXZkREFlRncweE9UQTJNVFV5TWpJMwpNVE5hRncweU9UQTJNVEl5TWpJM01UTmFNQjh4SFRBYkJnTlZCQU1URkdWc1pXTjBjbTl1TG1KMWFXeGtMbXh2ClkyRnNNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVubWZwTlhXOHVGRmk5czRaanl6d2tyM2EKbnBWSnFGdGszclBsa2owdzVGWGk3UmZubXFIa1pLOUdZK0kyL1VnMEROQmtLNFVUbFNEdkh3bXlGU3hNSEtORwpNRVF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXCmdCU1diVHk4RjdnSlEwQTVOQTNsblZFMU44bU9OakFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUFXTk1HMmQyYUQKMjJtMjVhODlyT0FDTG1DWUlUNjVoOHgzTmpxYVNseXozZ0loQU11bnVWQ1piaXZpRGlJbU54UFE2a0d6WHJNbgo0ZktHSmcrNFZXdHF0ZXFpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lSQUo2bFdvSXJuaTFCdkt6dDJjekxvNXd3Q2dZSUtvWkl6ajBFQXdJd0pERWkKTUNBR0ExVUVBeE1aWld4bFkzUnliMjR1WW5WcGJHUXViRzlqWVd3Z2NtOXZkREFlRncweE9UQTJNVFV5TWpJMwpNVE5hRncweU9UQTJNVEl5TWpJM01UTmFNQ1F4SWpBZ0JnTlZCQU1UR1dWc1pXTjBjbTl1TG1KMWFXeGtMbXh2ClkyRnNJSEp2YjNRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVnlkdXVDVDJhY3VrMlFIMDYKeWFsL2I2TzdlVFRwT0hrM1VjamMrWlp0YTJ2QzIrYzFJS2NTQXdpbUtiVGJLK25SeFdXSmw5Wll4OVJUd2JSZgpRakQ2bzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVsbTA4dkJlNENVTkFPVFFONVoxUk5UZkpqall3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVDROSkRRQWsKeFhaWkEzZ2hHRmpmYzBJdjY1bUpyT2VsR0dOMzNvSzNpQjBDSVFDS1VDU3RpSU1VS1JyOHBvWU42MzY5MWRjaAowa1ZMRnJnRC82eUVUbVNBcXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUQ4YndmS2tjMER5eFJudHhvSUwrN3hLdmtieUpLTXk1ZitybUxxc0djcFlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbm1mcE5YVzh1RkZpOXM0Wmp5endrcjNhbnBWSnFGdGszclBsa2owdzVGWGk3UmZubXFIawpaSzlHWStJMi9VZzBETkJrSzRVVGxTRHZId215RlN4TUhBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: tls-8fb2mddt4h
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: builder
spec:
  ports:
  - nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: builder
  type: NodePort
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: builder
  name: builder
spec:
  selector:
    matchLabels:
      app: builder
  template:
    metadata:
      labels:
        app: builder
    spec:
      containers:
      - env:
        - name: BUILDER_HOST
          value: 0.0.0.0
        - name: USE_EMBEDDED_ETCD
          value: "true"
        image: electronuserland/build-service-builder@sha256:301dcecab968c62263292a2799c83b03b349b80a6296b411f6b9fd00baf4267f
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 300
          successThreshold: 1
          timeoutSeconds: 2
        name: builder
        ports:
        - containerPort: 443
          hostPort: 443
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health-check
            port: 443
            scheme: HTTPS
          periodSeconds: 1
          successThreshold: 2
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/secrets
          name: tls
          readOnly: true
        - mountPath: /builder-tmp
          name: tmp
        - mountPath: /builder-embedded-etcd
          name: embedded-etcd
      terminationGracePeriodSeconds: 300
      volumes:
      - name: tls
        secret:
          secretName: tls-8fb2mddt4h
      - emptyDir:
          medium: Memory
        name: tmp
      - emptyDir:
          medium: Memory
        name: embedded-etcd
