apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "3"
  labels:
    workload.user.cattle.io/workloadselector: daemonSet-default-builder
  name: builder
  namespace: default
  selfLink: /apis/apps/v1beta2/namespaces/default/daemonsets/builder
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: daemonSet-default-builder
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":443,"dnsName":"builder-hostport","hostPort":443,"kind":"HostPort","name":"443tcp4430","protocol":"TCP","sourcePort":443}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: daemonSet-default-builder
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: builder
                operator: In
                values:
                - "true"
      containers:
      - image: electronuserland/build-service-builder@sha256:0c496a789ec2e8dcadca32f5c4bea36ca06f52dfa2ab5baadb145d6b75819884
        imagePullPolicy: Always
        name: builder
        ports:
        - containerPort: 443
          hostPort: 443
          name: 443tcp4430
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/secrets
          name: tls
          readOnly: true
        - mountPath: /builder-tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls
        secret:
          defaultMode: 256
          optional: false
          secretName: tls
      - emptyDir:
          medium: Memory
        name: tmp
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 3
  updatedNumberScheduled: 1

