---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  labels: &LABELS
    app: router
spec:
  selector:
    matchLabels: *LABELS
  template:
    metadata:
      labels: *LABELS
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: router
                operator: In
                values:
                - "true"
      containers:
      - image: electronuserland/build-service-router@sha256:809dadc31df6b103f305650d9c2276b1d6abe4ecf2ab2a4b07df792bc0cad928
        name: router
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/secrets
          name: tls
          readOnly: true

        readinessProbe:
          httpGet:
            path: /health-check
            port: 443
            scheme: HTTPS
          failureThreshold: 3
          periodSeconds: 1
          successThreshold: 2
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health-check
            port: 443
            scheme: HTTPS
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 300
          successThreshold: 1
          timeoutSeconds: 2

      volumes:
      - name: tls
        secret:
          secretName: tls
---
apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  selector:
    app: router
  ports:
  - port: 443
  externalIPs:
  - 51.38.69.239
