secrets:
  builder.crt.v3:
    external: true
  builder.key.v1:
    external: true
services:
  builder:
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
        - node.labels.builder == true
    environment:
      BUILDER_HOST: null
      BUILDER_PORT: null
      DEBUG: null
      PREFERRED_IP_VERSION: null
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-service-builder@sha256:17ed20ac7393077e0dc0f81289f32f9907eb1cb8343d01edfc06ddca54ba817c
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v3
      target: /etc/secrets/tls.cert
    - source: builder.key.v1
      target: /etc/secrets/tls.key
    volumes:
    - target: /builder-tmp
      type: tmpfs
  etcd-cluster-client:
    command:
    - --name=etcd
    - --advertise-client-urls=http://etcd:2379
    - --listen-client-urls=http://0.0.0.0:2379
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
        - node.labels.admin == true
    entrypoint: /usr/local/bin/etcd
    image: gcr.io/etcd-development/etcd@sha256:87921b377d5696461975582fc8a4d2ed0b7991ad82afbc4cbe68ef383ff6c295
    ports:
    - mode: host
      published: 2379
      target: 2379
  router:
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.labels.admin == true
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-service-router@sha256:5a57c2ec691503ff06a41ae6948ee99978a509ed9fa968c7d29ae3a8bc908940
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v3
      target: /etc/secrets/tls.cert
    - source: builder.key.v1
      target: /etc/secrets/tls.key
version: '3.4'

