secrets:
  builder.crt.v2:
    external: true
  builder.key.v1:
    external: true
  redis.v2:
    external: true
services:
  builder:
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
        - node.labels.builder == true
    environment:
      AGENT_HOST: null
      AGENT_PORT: null
      DEBUG: null
      PREFERRED_IP_VERSION: null
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-service-builder@sha256:bcdeac7e07a1a410b94e1ebb8b28568a93fa8d38b583b5fbc3280ae64686293f
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v2
      target: bundle.crt
    - source: builder.key.v1
      target: node.key
    volumes:
    - target: /builder-tmp
      type: tmpfs
  etcd-1:
    command:
    - --name=etcd-1
    - --initial-advertise-peer-urls=http://etcd-1:2380
    - --listen-peer-urls=http://0.0.0.0:2380
    - --advertise-client-urls=http://0.0.0.0:2379
    - --initial-cluster-token=mys3cr3tok3n
    - --heartbeat-interval=250
    - --election-timeout=1250
    - --initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
    - --initial-cluster-state=new
    deploy:
      endpoint_mode: dnsrr
    entrypoint: /usr/local/bin/etcd
    image: quay.io/coreos/etcd@sha256:75955f97f6b6ce1c6f363f50f99570bbbd87516b4212d0b3acdbd48039d51dbd
  etcd-2:
    command:
    - --name=etcd-2
    - --initial-advertise-peer-urls=http://etcd-2:2380
    - --listen-peer-urls=http://0.0.0.0:2380
    - --listen-client-urls=http://0.0.0.0:2379
    - --advertise-client-urls=http://etcd-2:2379
    - --initial-cluster-token=mys3cr3tok3n
    - --heartbeat-interval=250
    - --election-timeout=1250
    - --initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
    - --initial-cluster-state=new
    deploy:
      endpoint_mode: dnsrr
    entrypoint: /usr/local/bin/etcd
    image: quay.io/coreos/etcd@sha256:75955f97f6b6ce1c6f363f50f99570bbbd87516b4212d0b3acdbd48039d51dbd
  etcd-3:
    command:
    - --name=etcd-3
    - --initial-advertise-peer-urls=http://etcd-3:2380
    - --listen-peer-urls=http://0.0.0.0:2380
    - --listen-client-urls=http://0.0.0.0:2379
    - --advertise-client-urls=http://etcd-3:2379
    - --initial-cluster-token=mys3cr3tok3n
    - --heartbeat-interval=250
    - --election-timeout=1250
    - --initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380
    - --initial-cluster-state=new
    deploy:
      endpoint_mode: dnsrr
    entrypoint: /usr/local/bin/etcd
    image: quay.io/coreos/etcd@sha256:75955f97f6b6ce1c6f363f50f99570bbbd87516b4212d0b3acdbd48039d51dbd
  router:
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.labels.admin == true
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-service-router@sha256:fce934b34e5afccdd4eb8e00d71c84d1b4106611e3111b6f7aa172a031c27a2a
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v2
      target: bundle.crt
    - source: builder.key.v1
      target: node.key
version: '3.4'

