secrets:
  builder.crt.v3:
    external: true
  builder.key.v1:
    external: true
services:
  builder:
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
        - node.labels.builder == true
    environment:
      BUILDER_HOST: null
      BUILDER_PORT: null
      DEBUG: null
      PREFERRED_IP_VERSION: null
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-service-builder@sha256:6de472d68a881406e4293f853a0a0e4703d737fb63bd7efbcb344ef49c867143
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v3
      target: /etc/secrets/tls.cert
    - source: builder.key.v1
      target: /etc/secrets/tls.key
    volumes:
    - target: /builder-tmp
      type: tmpfs
  etcd-cluster-client:
    command:
    - --name=etcd
    - --advertise-client-urls=http://etcd:2379
    - --listen-client-urls=http://0.0.0.0:2379
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
        - node.labels.admin == true
    entrypoint: /usr/local/bin/etcd
    image: gcr.io/etcd-development/etcd@sha256:0d79c080d14053e90f22ad09e261c48bf83d296967b8e772d47250f72df6877b
    ports:
    - mode: host
      published: 2379
      target: 2379
  router:
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.labels.admin == true
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-service-router@sha256:75cd53b315bbdd8ea118fbaff2addea82c705a0eb5d2578f182003baa7f13ccf
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v3
      target: /etc/secrets/tls.cert
    - source: builder.key.v1
      target: /etc/secrets/tls.key
version: '3.4'

