configs:
  router-nginx.conf.v2:
    external: true
secrets:
  builder.crt.v2:
    external: true
  builder.key.v1:
    external: true
  redis.v2:
    external: true
services:
  router:
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.labels.admin == true
    environment:
      DEBUG: null
      REDIS_ENDPOINT: null
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: electronuserland/build-server-router@sha256:cd7466b2536d62a55795f3ae6a23938a4f331d63418f2cf79cefbb949894d5c6
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    secrets:
    - source: redis.v2
      target: /run/secrets/redis
    volumes:
    - socket:/socket:rw
  router-nginx:
    configs:
    - source: router-nginx.conf.v2
      target: /etc/nginx/nginx.conf
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.labels.admin == true
    hostname: '{{.Node.ID}}-{{.Service.Name}}'
    image: develar/nginx-pushstream@sha256:2f74affd13515882e57f2e6ca7e7a7ffc4ba343b80be67c4fcce5e20c634c2da
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 4m
    ports:
    - mode: host
      published: 443
      target: 443
    secrets:
    - source: builder.crt.v2
      target: bundle.crt
    - source: builder.key.v1
      target: node.key
    volumes:
    - socket:/socket:rw
version: '3.4'
volumes:
  socket: {}

