# must be daemon set because client downloads from server directly
# it is possible to use special prefix for pod and use ingress but this huge complication doesn't worth, so, we just expose as host port
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: builder
  labels: &LABELS
    app: builder
spec:
  selector:
    matchLabels: *LABELS
  template:
    metadata:
      labels: *LABELS
    spec:
      containers:
        - image: electronuserland/build-service-builder@sha256:e484318f2ce17a3d99d30b9658e4dd9e5b5eb989cb38b8f82fe4a58bf20442cf
          name: builder
          ports:
            - containerPort: 443
              hostPort: 443
          volumeMounts:
            - mountPath: /etc/secrets
              name: tls
              readOnly: true
            - mountPath: /builder-tmp
              name: tmp

          readinessProbe:
            httpGet:
              path: /health-check
              port: 443
              scheme: HTTPS
            failureThreshold: 3
            periodSeconds: 1
            successThreshold: 2
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health-check
              port: 443
              scheme: HTTPS
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 2

      # allow to complete running jobs (5 minutes)
      terminationGracePeriodSeconds: 300
      volumes:
        - name: tls
          secret:
            secretName: tls
        - name: tmp
          emptyDir:
            medium: Memory
